export const ActionTypes = {
  CREATE_AUTHOR: 'CREATE_AUTHOR',
  UPDATE_AUTHOR: 'UPDATE_AUTHOR',
  DELETE_AUTHOR: 'DELETE_AUTHOR',
  AUTHORS_LOADED: 'AUTHORS_LOADED',
  CREATE_COURSE: 'CREATE_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
  GET_COURSE: 'GET_COURSE',
  LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
  INITIALIZE: 'INITIALIZE',
}
